name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for PyPI Trusted Publishers
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0   # required so hatch-vcs can see tags
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Build sdist/wheel
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine
          python -m build
          python -m twine check dist/*
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1